import type { CaseStudy, Portfolio, ProofPoint } from "./types";

const RESUME_SOURCE_ID = "darshil-resume";
const RESUME_ARTIFACT_ID = "darshil-resume-pdf";

const resumeProof = (
  id: string,
  label: string,
  value: number,
  unit: string,
  summary: string,
  period: string,
  caseStudyIds: string[],
): ProofPoint => ({
  id,
  label,
  value,
  unit,
  summary,
  period,
  status: "self-reported",
  sourceIds: [RESUME_SOURCE_ID],
  caseStudyIds,
});

const resumeCase = (
  caseStudy: Omit<CaseStudy, "artifactIds" | "relatedIds"> & {
    artifactIds?: string[];
    relatedIds?: string[];
  },
): CaseStudy => ({
  ...caseStudy,
  artifactIds: caseStudy.artifactIds ?? [RESUME_ARTIFACT_ID],
  relatedIds: caseStudy.relatedIds ?? [],
});

const caseStudies: CaseStudy[] = [
  resumeCase({
    id: "r1",
    slug: "figmenta-operations-intern",
    title: "Operations Internship at Figmenta",
    organization: "Figmenta",
    role: "Operations Intern",
    period: "Jan 2026 – Feb 2026",
    kind: "experience",
    recruiterTakeaway:
      "Built operating visibility and reusable hiring workflows for an Asia team.",
    situation:
      "The Asia team needed shared project visibility and structured hiring and onboarding workflows.",
    actions: [
      "Built and managed a centralized project-tracking dashboard in Notion and Excel.",
      "Screened resumes, shortlisted candidates, managed onboarding, and created reusable onboarding decks.",
    ],
    result:
      "The résumé reports improved workflow visibility, timely task execution, and reusable hiring workflows.",
    proofIds: [
      "figmenta-projects",
      "figmenta-team-members",
      "figmenta-resumes",
      "figmenta-shortlisted",
      "figmenta-hires",
    ],
    skills: [
      "Project Management",
      "Process Optimization",
      "Microsoft Excel",
      "Notion",
    ],
  }),
  resumeCase({
    id: "r2",
    slug: "psr-compliance-operations-intern",
    title: "Operations Internship at PSR Compliance",
    organization: "PSR Compliance",
    role: "Operations Intern",
    period: "June 2025 – August 2025",
    kind: "experience",
    recruiterTakeaway:
      "Managed compliance operations through a team transition and supported commercial outcomes.",
    situation:
      "A team transition created a need for continuity across client compliance workflows.",
    actions: [
      "Managed compliance workflows and coordinated directly with company leadership.",
      "Mentored incoming interns and supported consulting, upsell, renewal, and service-expansion work.",
    ],
    result:
      "The résumé reports continuity in client work and support for retention and monetization.",
    proofIds: ["psr-clients"],
    skills: [
      "Stakeholder Management",
      "Business Development",
      "Process Optimization",
    ],
  }),
  resumeCase({
    id: "r3",
    slug: "mj-marketing-human-resources-intern",
    title: "Human Resources Internship at MJ Marketing Consultancy",
    organization: "MJ Marketing Consultancy",
    role: "Human Resource Intern",
    period: "March 2025 – June 2025",
    kind: "experience",
    recruiterTakeaway:
      "Applied structured analysis and coordination to a high-volume recruitment pipeline.",
    situation:
      "The recruitment pipeline needed better visibility, structured screening, and coordinated execution.",
    actions: [
      "Managed and analyzed candidate profiles to support data-driven screening.",
      "Coordinated interviews and conducted initial candidate assessments.",
    ],
    result:
      "The résumé reports improved pipeline visibility and support for informed shortlisting and workforce planning.",
    proofIds: ["mj-profiles", "mj-interviews", "mj-assessments"],
    skills: ["Stakeholder Management", "Process Optimization", "Google Sheets"],
  }),
  resumeCase({
    id: "p1",
    slug: "zautoai-strategy-consulting",
    title: "ZautoAI Strategy Consulting Engagement",
    organization: "ZautoAI",
    role: "Strategy Consultant, team project",
    period: "Nov 2025 – Dec 2025",
    kind: "project",
    recruiterTakeaway:
      "Connected market evidence to go-to-market, pricing, and positioning recommendations.",
    situation:
      "An AI healthcare startup needed market, competitive, go-to-market, pricing, and positioning analysis.",
    actions: [
      "Conducted market and competitive analysis.",
      "Developed recommendations and presented strategic insights to the founder as part of a team project.",
    ],
    result:
      "The résumé says the work contributed to the startup team's selection as a competition finalist.",
    proofIds: [],
    skills: [
      "Market Research",
      "Competitive Analysis",
      "Strategic Analysis",
      "Business Development",
    ],
  }),
  resumeCase({
    id: "p2",
    slug: "iit-guwahati-consulting-analytics-capstone",
    title: "Telemedicine Consulting and Analytics Capstone",
    organization: "IIT Guwahati Consulting & Analytics Club",
    role: "Program participant",
    period: "Dec 2025 – Jan 2026",
    kind: "project",
    recruiterTakeaway:
      "Turned a service-adoption problem into a phased product and process intervention.",
    situation:
      "A telemedicine platform was experiencing high appointment no-show rates.",
    actions: [
      "Analyzed the no-show problem and designed a phased product and process intervention.",
      "Incorporated onboarding, behavioral nudges, and an experimentation framework.",
    ],
    result:
      "The résumé reports recognition in the program's upper participant cohort.",
    proofIds: ["iitg-participant-percentile"],
    skills: ["Strategic Analysis", "Product Analysis", "Process Optimization"],
    relatedIds: ["a4", "c2"],
  }),
  resumeCase({
    id: "p3",
    slug: "haldirams-international-expansion",
    title: "Haldiram's International Expansion Strategy",
    organization: "Academic team project",
    role: "Strategy contributor, team project",
    period: "April 2025 – May 2025",
    kind: "project",
    recruiterTakeaway:
      "Evaluated market-entry constraints and translated them into expansion recommendations.",
    situation:
      "The team examined regulatory, supply-chain, and localization challenges in international expansion.",
    actions: [
      "Evaluated tariffs, supply-chain constraints, and cultural localization considerations.",
      "Developed strategic recommendations as part of the team project.",
    ],
    result:
      "The team produced a publication-ready business case, as described in the résumé.",
    proofIds: [],
    skills: ["Market Research", "Competitive Analysis", "Strategic Analysis"],
  }),
  resumeCase({
    id: "p4",
    slug: "zomato-metrics-trends-dashboard",
    title: "Zomato Metrics and Trends Dashboard",
    organization: "Individual project",
    role: "Dashboard creator",
    period: "Sep 2024 – Oct 2024",
    kind: "project",
    recruiterTakeaway:
      "Built an interactive dashboard to surface marketplace performance patterns.",
    situation:
      "Marketplace performance data needed an interactive view for trend identification.",
    actions: [
      "Built an interactive Google Looker Studio dashboard.",
      "Analyzed restaurant ratings, order growth, customer demographics, and other business measures.",
    ],
    result:
      "The individual project enabled data-driven trend identification, according to the résumé.",
    proofIds: ["zomato-metrics"],
    skills: ["Product Analysis", "Google Sheets"],
  }),
  resumeCase({
    id: "l1",
    slug: "igniters-club-founder-president",
    title: "Founder and President of Igniters Club",
    organization: "Igniters Club, powered by Unstop",
    role: "Founder & President",
    period: "Sep 2025 – May 2026",
    kind: "leadership",
    recruiterTakeaway:
      "Built a student organization and led a large management-fest delivery effort.",
    situation:
      "The institute chapter was founded and needed a membership base, leadership structure, and flagship programming.",
    actions: [
      "Founded the chapter and established its cross-functional leadership structure.",
      "Led Converge and its participant, guest, sponsorship, and partnership work.",
    ],
    result:
      "The résumé reports chapter growth and a management fest with substantial participation and partnership value.",
    proofIds: [
      "igniters-members",
      "igniters-leaders",
      "igniters-departments",
      "converge-participants",
      "converge-sponsorship",
    ],
    skills: [
      "Stakeholder Management",
      "Project Management",
      "Business Development",
    ],
  }),
  resumeCase({
    id: "a1",
    slug: "national-business-plan-championship-finalist",
    title: "National Business Plan Championship Finalist",
    organization: "IIM Bangalore × MakeIntern",
    role: "Finalist",
    period: "Date not listed in résumé",
    kind: "achievement",
    recruiterTakeaway:
      "Résumé-listed finalist recognition in a national business-plan competition.",
    situation:
      "The résumé lists participation in a national business-plan championship.",
    actions: ["Advanced to the finalist stage."],
    result: "Listed as a finalist in the résumé.",
    proofIds: [],
    skills: ["Strategic Analysis", "Business Development"],
  }),
  resumeCase({
    id: "a2",
    slug: "iim-calcutta-product-decode",
    title: "Product Decode Recognition",
    organization: "Indian Institute of Management Calcutta",
    role: "Competition participant",
    period: "Date not listed in résumé",
    kind: "achievement",
    recruiterTakeaway:
      "Résumé-listed national placement in a product-analysis competition.",
    situation: "The résumé lists participation in Product Decode.",
    actions: ["Completed the competition entry."],
    result: "The résumé reports a national placement.",
    proofIds: ["product-decode-rank"],
    skills: ["Product Analysis", "Strategic Analysis"],
  }),
  resumeCase({
    id: "a3",
    slug: "bplan-showdown-winner",
    title: "BPlan Showdown Winner",
    organization: "BPlan Showdown",
    role: "Winner",
    period: "Date not listed in résumé",
    kind: "achievement",
    recruiterTakeaway: "Résumé-listed win in a business-plan competition.",
    situation:
      "The résumé lists participation in the BPlan Showdown Business Plan Competition.",
    actions: ["Completed the competition entry."],
    result: "Listed as the winner in the résumé.",
    proofIds: [],
    skills: ["Strategic Analysis", "Business Development"],
  }),
  resumeCase({
    id: "a4",
    slug: "iit-guwahati-winter-consulting-program-recognition",
    title: "Winter Consulting Program Recognition",
    organization: "IIT Guwahati Consulting & Analytics Club",
    role: "Program participant",
    period: "Dec 2025 – Jan 2026",
    kind: "achievement",
    recruiterTakeaway:
      "Résumé-listed recognition in a consulting and analytics program.",
    situation:
      "The résumé lists participation in the Winter Consulting Program.",
    actions: ["Completed the consulting and analytics capstone."],
    result:
      "The résumé reports recognition in the program's upper participant cohort.",
    proofIds: ["iitg-participant-percentile"],
    skills: ["Strategic Analysis", "Product Analysis"],
    relatedIds: ["p2", "c2"],
  }),
  resumeCase({
    id: "e1",
    slug: "bba-business-and-industry",
    title: "BBA in Business and Industry",
    organization: "Maharaja Surajmal Institute, GGSIPU",
    role: "Student",
    period: "2024–2027",
    kind: "education",
    recruiterTakeaway: "Current undergraduate study in business and industry.",
    situation: "Undergraduate education listed in the résumé.",
    actions: ["Pursuing the BBA Business and Industry program."],
    result: "The résumé reports the current cumulative grade-point average.",
    proofIds: ["bba-cgpa"],
    skills: ["Strategic Analysis", "Market Research"],
  }),
  resumeCase({
    id: "e2",
    slug: "senior-secondary-education",
    title: "Senior Secondary Education",
    organization: "Lovely Public Sr. Sec. School, Priyadarshini Vihar",
    role: "Student",
    period: "2024",
    kind: "education",
    recruiterTakeaway: "Senior secondary education recorded in the résumé.",
    situation: "Senior secondary education listed in the résumé.",
    actions: ["Completed senior secondary education."],
    result: "The résumé reports the final percentage.",
    proofIds: ["class-xii-percentage"],
    skills: [],
  }),
  resumeCase({
    id: "c1",
    slug: "hult-prize-global-entrepreneurship-bootcamp",
    title: "Global Entrepreneurship Bootcamp",
    organization: "Hult Prize IIT Bombay",
    role: "Certificate holder",
    period: "2026",
    kind: "education",
    recruiterTakeaway: "Résumé-listed entrepreneurship bootcamp certification.",
    situation: "The certification is listed in the résumé.",
    actions: ["Completed the listed bootcamp."],
    result:
      "Completion is self-reported through the résumé; no separate certificate is stored in the repository.",
    proofIds: [],
    skills: ["Business Development"],
  }),
  resumeCase({
    id: "c2",
    slug: "winter-consulting-program-certificate",
    title: "Winter Consulting Program",
    organization: "IIT Guwahati Consulting & Analytics Club",
    role: "Certificate holder",
    period: "2025",
    kind: "education",
    recruiterTakeaway: "Résumé-listed consulting-program certification.",
    situation: "The certification is listed in the résumé.",
    actions: ["Completed the listed program."],
    result:
      "Completion is self-reported through the résumé; no separate certificate is stored in the repository.",
    proofIds: ["iitg-participant-percentile"],
    skills: ["Strategic Analysis", "Product Analysis"],
    relatedIds: ["p2", "a4"],
  }),
  resumeCase({
    id: "c3",
    slug: "business-intelligence-data-analysis-certificate",
    title: "Business Intelligence and Data Analysis",
    organization: "Indian Institute of Management Bangalore",
    role: "Certificate holder",
    period: "2024",
    kind: "education",
    recruiterTakeaway:
      "Résumé-listed business-intelligence and data-analysis certification.",
    situation: "The certification is listed in the résumé.",
    actions: ["Completed the listed program."],
    result:
      "Completion is self-reported through the résumé; no separate certificate is stored in the repository.",
    proofIds: [],
    skills: ["Product Analysis", "Microsoft Excel"],
  }),
];

export const portfolio: Portfolio = {
  candidate: {
    name: "Darshil Jain",
    headline: "Business, strategy, and operations undergraduate",
    summary:
      "BBA Business and Industry student with résumé-listed experience across operations, recruitment, consulting, analytics, and student leadership.",
    email: "darshijain0809@gmail.com",
    phone: "+91 9268264843",
    linkedInUrl: "https://www.linkedin.com/in/darshil-jain-611a3332b",
    resumeUrl: "/Darshil_Jain_Resume.pdf",
    skills: [
      "Market Research",
      "Competitive Analysis",
      "Strategic Analysis",
      "Business Development",
      "Stakeholder Management",
      "Project Management",
      "Product Analysis",
      "Process Optimization",
      "Microsoft Excel",
      "Google Sheets",
      "Canva",
      "Notion",
    ],
  },
  sources: [
    {
      id: RESUME_SOURCE_ID,
      title: "Darshil Jain résumé",
      kind: "resume",
      url: "/Darshil_Jain_Resume.pdf",
      note: "Candidate-authored source; claims are self-reported unless a separate source is attached.",
    },
  ],
  proofPoints: [
    resumeProof(
      "figmenta-projects",
      "Projects tracked",
      35,
      "+ projects",
      "Projects covered by the centralized dashboard.",
      "Jan 2026 – Feb 2026",
      ["r1"],
    ),
    resumeProof(
      "figmenta-team-members",
      "Team members supported",
      15,
      "+ team members",
      "Asia team members covered by the dashboard.",
      "Jan 2026 – Feb 2026",
      ["r1"],
    ),
    resumeProof(
      "figmenta-resumes",
      "Résumés screened",
      500,
      "+ résumés",
      "Résumés screened during hiring support.",
      "Jan 2026 – Feb 2026",
      ["r1"],
    ),
    resumeProof(
      "figmenta-shortlisted",
      "Candidates shortlisted",
      100,
      "+ candidates",
      "Candidates shortlisted during hiring support.",
      "Jan 2026 – Feb 2026",
      ["r1"],
    ),
    resumeProof(
      "figmenta-hires",
      "Hires onboarded",
      5,
      "+ hires",
      "Hires whose onboarding was managed.",
      "Jan 2026 – Feb 2026",
      ["r1"],
    ),
    resumeProof(
      "psr-clients",
      "Client workflows managed",
      70,
      "+ clients",
      "Clients covered during a team transition.",
      "June 2025 – August 2025",
      ["r2"],
    ),
    resumeProof(
      "mj-profiles",
      "Candidate profiles analyzed",
      500,
      "+ profiles",
      "Candidate profiles managed and analyzed.",
      "March 2025 – June 2025",
      ["r3"],
    ),
    resumeProof(
      "mj-interviews",
      "Interviews coordinated",
      100,
      "+ interviews",
      "Interviews coordinated during the internship.",
      "March 2025 – June 2025",
      ["r3"],
    ),
    resumeProof(
      "mj-assessments",
      "Candidates assessed",
      300,
      "+ candidates",
      "Candidates given initial assessments.",
      "March 2025 – June 2025",
      ["r3"],
    ),
    resumeProof(
      "iitg-participant-percentile",
      "Program recognition",
      10,
      "top percent",
      "Participant cohort reported by the résumé.",
      "Dec 2025 – Jan 2026",
      ["p2", "a4", "c2"],
    ),
    resumeProof(
      "zomato-metrics",
      "Business metrics analyzed",
      5,
      "+ metrics",
      "Metrics included in the Looker Studio dashboard.",
      "Sep 2024 – Oct 2024",
      ["p4"],
    ),
    resumeProof(
      "igniters-members",
      "Chapter members",
      80,
      "+ members",
      "Members reported after chapter growth.",
      "Sep 2025 – May 2026",
      ["l1"],
    ),
    resumeProof(
      "igniters-leaders",
      "Leadership team",
      17,
      "members",
      "Members in the chapter leadership structure.",
      "Sep 2025 – May 2026",
      ["l1"],
    ),
    resumeProof(
      "igniters-departments",
      "Functional departments",
      4,
      "departments",
      "Departments in the chapter leadership structure.",
      "Sep 2025 – May 2026",
      ["l1"],
    ),
    resumeProof(
      "converge-participants",
      "Converge participants",
      1000,
      "+ participants",
      "Participants reported for Converge.",
      "2026",
      ["l1"],
    ),
    resumeProof(
      "converge-sponsorship",
      "Sponsorship and partnership value",
      50000,
      "+ INR",
      "Value reported for sponsorships and partnerships.",
      "2026",
      ["l1"],
    ),
    resumeProof(
      "product-decode-rank",
      "National placement",
      4,
      "position",
      "Placement reported for Product Decode.",
      "Date not listed in résumé",
      ["a2"],
    ),
    resumeProof(
      "bba-cgpa",
      "Cumulative grade-point average",
      9.39,
      "CGPA",
      "Current BBA result listed in the résumé.",
      "2024–2027",
      ["e1"],
    ),
    resumeProof(
      "class-xii-percentage",
      "Senior secondary result",
      88,
      "%",
      "Final result listed in the résumé.",
      "2024",
      ["e2"],
    ),
  ],
  artifacts: [
    {
      id: RESUME_ARTIFACT_ID,
      title: "Darshil Jain résumé PDF",
      kind: "document",
      url: "/Darshil_Jain_Resume.pdf",
      alt: "Darshil Jain's résumé containing education, experience, projects, leadership, achievements, skills, and certifications.",
      provenance: "Candidate-provided PDF stored in the public repository.",
      sourceIds: [RESUME_SOURCE_ID],
      status: "self-reported",
    },
  ],
  caseStudies,
  collections: [
    {
      id: "experience",
      slug: "experience",
      title: "Experience",
      description: "Operations and recruitment internships.",
      cover: "/artifacts/experience.svg",
      gradient: "linear-gradient(135deg,#36c6ff,#2536ff)",
      caseStudyIds: ["r1", "r2", "r3"],
    },
    {
      id: "projects",
      slug: "projects",
      title: "Projects",
      description: "Selected consulting, strategy, and analytics work.",
      cover: "/artifacts/projects.svg",
      gradient: "linear-gradient(135deg,#8e2de2,#4a00e0)",
      caseStudyIds: ["p1", "p2", "p3", "p4"],
    },
    {
      id: "skills",
      slug: "skills",
      title: "Skills in context",
      description: "Skills linked to the work where they were applied.",
      cover: "/artifacts/skills.svg",
      gradient: "linear-gradient(135deg,#ff4d6d,#7b2ff7)",
      caseStudyIds: ["r1", "r2", "r3", "p1", "p2", "p3", "p4", "l1"],
    },
    {
      id: "certs",
      slug: "certifications",
      title: "Certifications",
      description: "Programs listed in the candidate-provided résumé.",
      cover: "/artifacts/certifications.svg",
      gradient: "linear-gradient(135deg,#1ed760,#0a5)",
      caseStudyIds: ["c1", "c2", "c3"],
    },
    {
      id: "achievements",
      slug: "achievements",
      title: "Achievements",
      description:
        "Competition results listed in the candidate-provided résumé.",
      cover: "/artifacts/achievements.svg",
      gradient: "linear-gradient(160deg,#4a00e0,#b3b3ff)",
      caseStudyIds: ["a1", "a2", "a3", "a4"],
    },
    {
      id: "education",
      slug: "education",
      title: "Education",
      description: "Academic record listed in the candidate-provided résumé.",
      cover: "/artifacts/education.svg",
      gradient: "linear-gradient(135deg,#f7971e,#ffd200)",
      caseStudyIds: ["e1", "e2"],
    },
  ],
  careerMixChapters: [
    {
      id: "operate",
      title: "Operate",
      summary: "Build visibility, workflows, and continuity.",
      caseStudyIds: ["r1", "r2", "r3"],
    },
    {
      id: "analyze",
      title: "Analyze",
      summary: "Turn research and data into practical recommendations.",
      caseStudyIds: ["p1", "p2", "p3", "p4"],
    },
    {
      id: "lead",
      title: "Lead",
      summary: "Build teams and deliver shared outcomes.",
      caseStudyIds: ["l1"],
    },
  ],
};
